165 issue untyped events and event listners
Hexastack/Hexabot pull request #166
Opened 2024-10-07 14:41 UTC by yassinedorbozgithub

# Motivation
 The main motivation is enhancing events typing 

Fixes #165

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (Storybook)
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2024-10-07 17:30 UTC, marrouchi requested changes

2024-10-07 17:30 UTC, marrouchi commented on api/src/utils/generics/base-repository.ts
>        await repository.preDelete(query, criteria);
Let's invert the order (for all)

2024-10-07 17:34 UTC, yassinedorbozgithub commented on api/src/utils/generics/base-repository.ts
>        await repository.preDelete(query, criteria);
Sure, i will do that :technologist:

2024-10-09 09:07 UTC, marrouchi approved these changes
@yassinedorbozgithub Looks perfect to me 👏 

Let's do PRs in the current extensions we have so that it doesn't break (primarely messenger for now)

2024-10-09 09:09 UTC, yassinedorbozgithub commented
> @yassinedorbozgithub Looks perfect to me 👏
> 
> Let's do PRs in the current extensions we have so that it doesn't break (primarely messenger for now)

Sure happy to do that :technologist:

2024-10-09 09:48 UTC, IkbelTalebHssan approved these changes

2024-10-09 16:19 UTC, merged