feat: add plugins settings i18n + typing
Hexastack/Hexabot pull request #249
Opened 2024-10-19 13:01 UTC by marrouchi

# Motivation

In this PR : 
- We introduce i18n for plugins 
- Enforce typing for plugin settings (arguments)
- Remove dummy plugin (keep it only for unit tests)

# Related PRs:
- https://github.com/Hexastack/hexabot-plugin-chatgpt/pull/2

# How to test:
- Install chatgpt plugin as an example 
- Add a block, check the block message form : inputs should be translated (including helper text)
- Test the block

# Type of change:

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-10-20 22:58 UTC, yassinedorbozgithub approved these changes

2024-10-21 07:34 UTC, yassinedorbozgithub requested changes
Hi @marrouchi, i have faced those typescript errors
![image](https://github.com/user-attachments/assets/af788427-2830-44c4-99b8-e835723d929f)

2024-10-21 08:01 UTC, IkbelTalebHssan reviewed
![image](https://github.com/user-attachments/assets/e9595f1c-778b-4957-b79d-4d37483f3ed6)
Hi,
I had this error when starting the project.

2024-10-21 09:44 UTC, yassinedorbozgithub approved these changes
Tested successfully with Gemini plugin including the updates of this PR : https://github.com/Hexastack/hexabot-plugin-gemini/pull/1
EN:
![image](https://github.com/user-attachments/assets/c3f7550b-a91d-49ae-9cc8-82cf92ed2376)
FR: 
![image](https://github.com/user-attachments/assets/10cbd51e-b85f-4a66-8d90-69c019fad69f)

LGTM :rocket:

2024-10-21 10:23 UTC, IkbelTalebHssan approved these changes

2024-10-21 10:56 UTC, merged