Update index.tsx
Hexastack/Hexabot pull request #26
Opened 2024-09-16 22:14 UTC by adititripathi

Search Input size increased

# Motivation

Bug fix to inrease the keyword size for input

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #16

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (Storybook)
- [ ] New and existing unit tests pass locally with my changes

2024-09-17 18:04 UTC, adititripathi commented
https://github.com/user-attachments/assets/b04aa697-af8f-4698-9ef3-cfbf70a8b9b2

2024-09-18 06:23 UTC, marrouchi reviewed
Thank you @adititripathi for your contribution 🙏

2024-09-18 06:23 UTC, marrouchi commented on frontend/src/components/subscribers/index.tsx
> +            }}
I don't think we need this.

2024-09-18 06:23 UTC, marrouchi commented on frontend/src/components/subscribers/index.tsx
> +          flexDirection="row"
By default, it's "row". So no need to specify it.

2024-09-18 06:23 UTC, marrouchi requested changes
Left you a couple of comments

2024-09-22 06:31 UTC, marrouchi commented
Closed in favor of https://github.com/Hexastack/Hexabot/pull/59

2024-09-22 06:31 UTC, closed without merging