feat(attachment-uploader): adding loadingindicator to AttachmentUploader component.
Hexastack/Hexabot pull request #275
Opened 2024-10-27 08:45 UTC by AuraOfDivinity

# Motivation

This PR adds a loading indicator to the AttachmentUploader component. The added LoadingIcon is reusable and takes in the size & color as props allowing it to be configured as necessary.

Fixes #153 

# Type of change:

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added unit tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2024-11-01 10:28 UTC, marrouchi approved these changes
@AuraOfDivinity Awesome !

2024-11-01 10:29 UTC, marrouchi requested changes
@AuraOfDivinity 👏

2024-11-01 10:29 UTC, marrouchi commented on frontend/src/app-components/attachment/AttachmentUploader.tsx
>    const { mutateAsync: uploadAttachment } = useUpload(EntityType.ATTACHMENT, {
You don't have to add an extra state :
```suggestion
  const { toast } = useToast();
  const { mutateAsync: uploadAttachment, isLoading } = useUpload(EntityType.ATTACHMENT, {
```

2025-04-12 11:35 UTC, yassinedorbozgithub commented on frontend/src/app-components/attachment/AttachmentUploader.tsx
>    const { mutateAsync: uploadAttachment } = useUpload(EntityType.ATTACHMENT, {
100%, as mentioned we can use useQuery isLoading state.
The the recommendation are implemented in a new [PR](https://github.com/Hexastack/Hexabot/pull/920)

2025-04-12 11:35 UTC, yassinedorbozgithub commented
Closed in favor of #920

2025-04-12 11:35 UTC, closed without merging