feat(api): Redis integration REST/WS
Hexastack/Hexabot pull request #335
Opened 2024-11-15 16:39 UTC by yassinedorbozgithub

# Motivation
The main motivation of this PR is integrate Redis.

Fixes #334

# Type of change:
- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:
- [x] I have performed a self-review of my own code
- [x] New and existing unit tests pass locally with my changes

2024-11-15 17:04 UTC, IkbelTalebHssan approved these changes

2024-11-17 09:17 UTC, marrouchi requested changes
Perfect ! Left some comments 👏

2024-11-17 09:17 UTC, marrouchi commented on api/src/config/index.ts
> +    host: process.env.REDIS_HOST,
```suggestion
    host: process.env.REDIS_HOST,
```
Let's add a default value (same as we have in our docker-compose.redis.yml)

2024-11-17 09:17 UTC, marrouchi commented on api/src/config/types.ts
> +} & { type: 'memory' | 'redis' };
```suggestion
  host: string;
  port: number;
  type: 'memory' | 'redis'
 };
```

2024-11-17 18:39 UTC, marrouchi approved these changes

2024-11-17 18:39 UTC, merged