feat: add merge workflow
Hexastack/Hexabot pull request #38
Opened 2024-09-18 11:28 UTC by Emnaghz

# Motivation

This workflow automates the process of building and pushing Docker images for different parts of the project when changes are pushed to the main branch or triggered manually.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (Storybook)
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-09-18 17:05 UTC, marrouchi requested changes
A general remark, I think we can may do the setup of docker and login once to build all the images.

2024-09-18 17:05 UTC, marrouchi commented on .github/workflows/merge.yml
> +          context: ./frontend
```suggestion
          context: ./
          file: ./frontend/Dockerfile
```

2024-09-18 17:05 UTC, marrouchi commented on .github/workflows/merge.yml
> +          context: ./widget
```suggestion
          context: ./
          file: ./widget/Dockerfile
```

2024-09-19 10:42 UTC, Emnaghz commented
In the updated workflow, I've optimized the process by separating the tasks into two distinct jobs:

**Job 1: Path Filtering**
    It filters the paths to determine which parts of the codebase have changed and outputs these results to be used by subsequent jobs.

**Job 2: Build and Push Docker Images**
    This job handles the setup of the building environment, the authentication as well as the conditional builds.

**Explanation:**
When I separated the Docker Hub login process and the environment setup from the build and push steps, I encountered several issues. Each job in GitHub Actions is executed in a separate environment, which means that the authentication status as well as the env setup wasn't shared between other jobs and resulted in many errors.

To address this, I had to ensure that the Docker Hub login and environment setup steps were completed in the same job as the build and push operations.

2024-09-20 08:22 UTC, marrouchi requested changes
I forgot that we need to build the docker image for nlu as well "hexabot-nlu"

2024-09-20 08:22 UTC, marrouchi commented on .github/workflows/merge.yml
> +          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hexabot-frontend:latest
```suggestion
          tags: hexastack/hexabot-ui:latest
```

2024-09-20 08:22 UTC, marrouchi commented on .github/workflows/merge.yml
> +          context: ./
```suggestion
          context: ./widget
```
I think we need to set the widget context like this. Can you push and check ?

2024-09-20 08:22 UTC, marrouchi commented on .github/workflows/merge.yml
> +          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hexabot-api:latest
```suggestion
          tags: hexastack/hexabot-api:latest
```

2024-09-20 16:08 UTC, merged