Fix/eslint prettier configuration
Hexastack/Hexabot pull request #399
Opened 2024-12-03 14:28 UTC by abdou6666

# Motivation

This PR addresses the issue of misaligned ESLint and Prettier configurations between the frontend and widget projects. It ensures that both projects share consistent configurations for code styling and linting, helping to maintain uniformity across the codebase

Fixes #322

# Type of change:

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

2024-12-03 15:07 UTC, marrouchi requested changes

2024-12-03 15:24 UTC, abdou6666 commented on widget/.eslintrc.json
>      "plugin:react-hooks/recommended"
Thanks for the feedback! Husky is working locally. I believe you were referring to the react plugin in the plugins section, and I've added it back. I'll also look into any necessary updates for the GitHub Actions configuration.

2024-12-04 15:32 UTC, marrouchi approved these changes

2024-12-04 15:48 UTC, yassinedorbozgithub requested changes

2024-12-04 15:48 UTC, yassinedorbozgithub commented on widget/src/components/messages/TextMessage.tsx
> +    if (message.direction === "received" && messageTextRef.current) {
```suggestion
    if (message.direction === Direction.received && messageTextRef.current) {
```

2024-12-04 15:54 UTC, yassinedorbozgithub commented on widget/src/components/ChatHeader.tsx
> +            rel="noreferrer"
Notice that this attribute is changed

2024-12-05 10:45 UTC, merged