fix: add production target to api
Hexastack/Hexabot pull request #95
Opened 2024-09-27 10:23 UTC by Emnaghz

# Motivation

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (Storybook)
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-09-27 23:01 UTC, Emnaghz commented
@yassinedorbozgithub ready to be tested! :rocket:

2024-09-28 03:23 UTC, yassinedorbozgithub commented
> @yassinedorbozgithub ready to be tested! 🚀

@Emnaghz, review process is started :technologist:

2024-09-29 06:50 UTC, yassinedorbozgithub approved these changes

2024-09-29 09:05 UTC, marrouchi requested changes

2024-09-29 09:05 UTC, marrouchi commented on api/Dockerfile
> +COPY --from=builder /app/ .
Copying the entire /app directory may include unnecessary files, increasing image size. Copy only the necessary build artifacts or directories needed for the application to run.

2024-09-29 11:11 UTC, marrouchi commented
Closed in favor of https://github.com/Hexastack/Hexabot/pull/98

2024-09-29 11:11 UTC, closed without merging